# Viseme Classification
input_stream: "mono_waveform"
output_stream: "viseme_category"

node {
  calculator: "RationalFactorResampleCalculator"
  input_stream: "mono_waveform"
  output_stream: "Resample:resampled_waveform"
  node_options: {
    [type.googleapis.com/mediapipe.RationalFactorResampleCalculatorOptions] {
      target_sample_rate: 16000.0
    }
  }
}

node {
calculator: "MfccCalculator"
input_stream:"Resample:resampled_waveform"
output_stream:"MFCC:mfcc_features"
node_options{
[type.googleapis.com/mediapipe.MfccCalculatorOptions]{
    mfcc_count:13
    } 
  }
}

node{
calculator:"SvmClassifier"
input_stream:"MFCC:mfcc_features"
output_stream:"viseme_category"

}